version: '3.1'
services:
    web:
        build:
            context: ./
            dockerfile: _docker/web-dev.docker
        command: npm run dev
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DB_PORT: 3306
            DB_HOST: db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P@55w0rd
            MYSQL_DATABASE: registration
        ports:
            - "33074:3306"
        volumes:
            - ./_docker/mysql-conf.d/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
